"""empty message

Revision ID: 01e5e8fed13e
Revises: 6342b66704d5
Create Date: 2020-07-08 14:50:05.231309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e5e8fed13e'
down_revision = '6342b66704d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.drop_constraint('movies_uploader_fkey', 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'users', ['uploader_id'], ['id'])
    op.drop_column('movies', 'uploader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('uploader', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key('movies_uploader_fkey', 'movies', 'users', ['uploader'], ['id'])
    op.drop_column('movies', 'uploader_id')
    # ### end Alembic commands ###
