"""empty message

Revision ID: 0fd7a1caa54b
Revises: 
Create Date: 2020-07-14 16:00:12.610902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd7a1caa54b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies_appear', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies_appear', 'id')
    # ### end Alembic commands ###
