"""empty message

Revision ID: 1e1d3cd94d43
Revises: 20418bab69b8
Create Date: 2020-07-10 09:44:50.818848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1d3cd94d43'
down_revision = '20418bab69b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'albums', 'users', ['artist_id'], ['id'])
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['author_id'], ['id'])
    op.add_column('tracks', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tracks', 'users', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_column('tracks', 'artist_id')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_column('albums', 'artist_id')
    # ### end Alembic commands ###
