"""empty message

Revision ID: 20418bab69b8
Revises: e9bebaa78d7a
Create Date: 2020-07-10 09:25:10.122708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20418bab69b8'
down_revision = 'e9bebaa78d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_album')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_album',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name='user_album_album_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_album_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_album_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'album_id', name='user_album_pkey')
    )
    # ### end Alembic commands ###
