"""empty message

Revision ID: 632acd9b944a
Revises: 7984d3f25df8
Create Date: 2020-07-10 09:48:51.269026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632acd9b944a'
down_revision = '7984d3f25df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('url', sa.String(), nullable=True))
    op.add_column('books', sa.Column('url', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'url')
    op.drop_column('books', 'url')
    op.drop_column('albums', 'url')
    # ### end Alembic commands ###
