"""empty message

Revision ID: 6342b66704d5
Revises: 
Create Date: 2020-07-08 14:45:13.135131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6342b66704d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('uploader', sa.Integer(), nullable=True))
    op.drop_constraint('movies_user_id_fkey', 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'users', ['uploader'], ['id'])
    op.drop_column('movies', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key('movies_user_id_fkey', 'movies', 'users', ['user_id'], ['id'])
    op.drop_column('movies', 'uploader')
    # ### end Alembic commands ###
