"""empty message

Revision ID: 71b6b723740b
Revises: 3f85918ff793
Create Date: 2020-07-21 11:54:01.667188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b6b723740b'
down_revision = '3f85918ff793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('album_cover_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'album_cover_url')
    # ### end Alembic commands ###
