"""empty message

Revision ID: a209f479f48e
Revises: ad1b126bb453
Create Date: 2020-07-10 12:49:09.326263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a209f479f48e'
down_revision = 'ad1b126bb453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['uploader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'uploader_id')
    # ### end Alembic commands ###
