"""empty message

Revision ID: a63b805eacca
Revises: e9996e8a6099
Create Date: 2020-07-07 16:38:52.020131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63b805eacca'
down_revision = 'e9996e8a6099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('region', sa.String(), nullable=True))
    op.drop_column('addresses', 'Region')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('Region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('addresses', 'region')
    # ### end Alembic commands ###
