"""empty message

Revision ID: ad1b126bb453
Revises: 632acd9b944a
Create Date: 2020-07-10 12:28:16.993283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1b126bb453'
down_revision = '632acd9b944a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'albums', 'users', ['uploader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_column('albums', 'uploader_id')
    # ### end Alembic commands ###
