"""empty message

Revision ID: bbeb226a4cc6
Revises: a209f479f48e
Create Date: 2020-07-10 13:26:56.939838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbeb226a4cc6'
down_revision = 'a209f479f48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'albums', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_column('albums', 'category_id')
    # ### end Alembic commands ###
