"""empty message

Revision ID: e9996e8a6099
Revises: 
Create Date: 2020-07-07 16:31:54.440704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9996e8a6099'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'Country')
    op.add_column('user_type', sa.Column('utype_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_type_role_id_fkey', 'user_type', type_='foreignkey')
    op.create_foreign_key(None, 'user_type', 'utypes', ['utype_id'], ['id'])
    op.drop_column('user_type', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_type', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_type', type_='foreignkey')
    op.create_foreign_key('user_type_role_id_fkey', 'user_type', 'roles', ['role_id'], ['id'])
    op.drop_column('user_type', 'utype_id')
    op.add_column('addresses', sa.Column('Country', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
